create table man(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fio varchar(100) UNIQUE NOT NULL,
    yearBirth int not null CHECK ( yearBirth > 0 )
);


create table book(
	id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	man_id int REFERENCES man(id) ON DELETE SET NULL,
	title varchar(100) NOT NULL,
	author varchar(100) NOT NULL,
	year int not null CHECK ( year > 0 )

);

drop table man;
drop table book;

insert into man (fio, yearBirth) values ('John Smith', 1990);
insert into man (fio, yearBirth) values ('Bob Dylan', 2016);
insert into man (fio, yearBirth) values ('David Beckham', 1975);
insert into man (fio, yearBirth) values ('Tom Holland', 1995);


insert into book (man_id, title, author, year) values (1, 'The Hobbit', 'Tolkien', 1937);
insert into book (man_id, title, author, year) values (1, 'Hotel', 'Arthur Hailey', 1965);
insert into book (man_id, title, author, year) values (3, 'Solaris', 'Stanislaw Herman Lem', 1961);
insert into book (man_id, title, author, year) values (4, 'Faust', 'Goethe', 1808);